---
npmName: kleisterjs
npmVersion: 3.4.0
supportsES6: true
useSingleRequestParameter: true
withNodeImports: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: model
enablePostProcessFile: true

...
