---
npmName: kleisterjs
npmVersion: 3.3.2
supportsES6: true
useSingleRequestParameter: true
withNodeImports: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: model
enablePostProcessFile: true

...
